backend:
  name: github
  repo: ericayamap/galix-site
  branch: main

media_folder: "images"
public_folder: "/images"

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Content", name: "body", widget: "text"}
